### ISSUE TITLE
-i version exists in script but is absent from README

### ISSUE THREAD

**Issue by johnsaigle** [lucacapacci/AlfrescoScan#1]
Hello! I just tried this out and noticed the tool didn't report any issues on the instance I was testing.

However, I also know there is a cert error on my targeted host.

I looked in the python and saw the `-i` flag which worked perfectly.

This should be added to the README and the displayed usage message. :)

**Comment by lucacapacci** [comment]
Hi John, Thanks for the issue, I forgot to put it in the readme, now it's ok
